In [2]:
import numpy as np

In [3]:
#請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
import random

def function1():
    np.random.seed(0)
    a = np.random.randint(0,100,1000*100*100)   
    #print(a)
    a.resize([1000,100,100])
    #print(a)
    return a+1

In [4]:
%timeit [print(function1().flatten())]

[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
158 ms ± 2.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
def function2():
    np.random.seed(0)
    a = np.random.randint(0,100,1000*100*100)  
    a.resize([1000,100,100]) 
    for i in range(len(a)):
        for j in range(len(a[i])):
            for k in range(len(a[i][j])):
                a[i][j][k]+=1
    return a

In [10]:
%timeit [print(function2().flatten())]

[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
[45 48 65 ... 37 28 45]
8.85 s ± 256 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [1]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
import numpy as np

#np.random.seed(0)
a = np.random.randint(0,100,100)   
b = a
c = a.reshape([2,50])
d = a.reshape(2,25,2)

print(b)
print(c) 
print(d)

[35 39 77 82 80 69 10 70  2 56 38 69 80 39 90  1 73 97 92 15 60 34 19 41
 81 93 16 60 65 38 27 46 19 32 66 26 54 13 87 52 36 52 83 47 79 81 37 33
  4 22 79 97 26 75 51 45 63 58  9 98 31 46 13 43 85 17 50 98  9 84 67 98
  4 48 20 81 70  2  6 68 44 78 79 91 24 68 47 82 60 39 59 98 89 18 49 52
 26 15  6 22]
[[35 39 77 82 80 69 10 70  2 56 38 69 80 39 90  1 73 97 92 15 60 34 19 41
  81 93 16 60 65 38 27 46 19 32 66 26 54 13 87 52 36 52 83 47 79 81 37 33
   4 22]
 [79 97 26 75 51 45 63 58  9 98 31 46 13 43 85 17 50 98  9 84 67 98  4 48
  20 81 70  2  6 68 44 78 79 91 24 68 47 82 60 39 59 98 89 18 49 52 26 15
   6 22]]
[[[35 39]
  [77 82]
  [80 69]
  [10 70]
  [ 2 56]
  [38 69]
  [80 39]
  [90  1]
  [73 97]
  [92 15]
  [60 34]
  [19 41]
  [81 93]
  [16 60]
  [65 38]
  [27 46]
  [19 32]
  [66 26]
  [54 13]
  [87 52]
  [36 52]
  [83 47]
  [79 81]
  [37 33]
  [ 4 22]]

 [[79 97]
  [26 75]
  [51 45]
  [63 58]
  [ 9 98]
  [31 46]
  [13 43]
  [85 17]
  [50 98]
  [ 9 84]
  [67 98]
  [ 4 48]
  [20 8

In [2]:
print(b.tolist())
print(c.tolist()) 
print(d.tolist())

print(list(b)) #elements are ndarrays
print(list(c)) #elements are ndarrays
print(list(d)) #elements are ndarrays

[35, 39, 77, 82, 80, 69, 10, 70, 2, 56, 38, 69, 80, 39, 90, 1, 73, 97, 92, 15, 60, 34, 19, 41, 81, 93, 16, 60, 65, 38, 27, 46, 19, 32, 66, 26, 54, 13, 87, 52, 36, 52, 83, 47, 79, 81, 37, 33, 4, 22, 79, 97, 26, 75, 51, 45, 63, 58, 9, 98, 31, 46, 13, 43, 85, 17, 50, 98, 9, 84, 67, 98, 4, 48, 20, 81, 70, 2, 6, 68, 44, 78, 79, 91, 24, 68, 47, 82, 60, 39, 59, 98, 89, 18, 49, 52, 26, 15, 6, 22]
[[35, 39, 77, 82, 80, 69, 10, 70, 2, 56, 38, 69, 80, 39, 90, 1, 73, 97, 92, 15, 60, 34, 19, 41, 81, 93, 16, 60, 65, 38, 27, 46, 19, 32, 66, 26, 54, 13, 87, 52, 36, 52, 83, 47, 79, 81, 37, 33, 4, 22], [79, 97, 26, 75, 51, 45, 63, 58, 9, 98, 31, 46, 13, 43, 85, 17, 50, 98, 9, 84, 67, 98, 4, 48, 20, 81, 70, 2, 6, 68, 44, 78, 79, 91, 24, 68, 47, 82, 60, 39, 59, 98, 89, 18, 49, 52, 26, 15, 6, 22]]
[[[35, 39], [77, 82], [80, 69], [10, 70], [2, 56], [38, 69], [80, 39], [90, 1], [73, 97], [92, 15], [60, 34], [19, 41], [81, 93], [16, 60], [65, 38], [27, 46], [19, 32], [66, 26], [54, 13], [87, 52], [36, 52], [8

In [3]:
def myfunction(ndarray):
    if type(ndarray) != np.ndarray:
        return ndarray

    #for i in np.nditer(ndarray):
    nd_list=list(ndarray)
    for i in range(len(nd_list)):
        nd_list[i] = myfunction(nd_list[i])
    return nd_list

print(myfunction(b))
print(myfunction(c))
print(myfunction(d))

[35, 39, 77, 82, 80, 69, 10, 70, 2, 56, 38, 69, 80, 39, 90, 1, 73, 97, 92, 15, 60, 34, 19, 41, 81, 93, 16, 60, 65, 38, 27, 46, 19, 32, 66, 26, 54, 13, 87, 52, 36, 52, 83, 47, 79, 81, 37, 33, 4, 22, 79, 97, 26, 75, 51, 45, 63, 58, 9, 98, 31, 46, 13, 43, 85, 17, 50, 98, 9, 84, 67, 98, 4, 48, 20, 81, 70, 2, 6, 68, 44, 78, 79, 91, 24, 68, 47, 82, 60, 39, 59, 98, 89, 18, 49, 52, 26, 15, 6, 22]
[[35, 39, 77, 82, 80, 69, 10, 70, 2, 56, 38, 69, 80, 39, 90, 1, 73, 97, 92, 15, 60, 34, 19, 41, 81, 93, 16, 60, 65, 38, 27, 46, 19, 32, 66, 26, 54, 13, 87, 52, 36, 52, 83, 47, 79, 81, 37, 33, 4, 22], [79, 97, 26, 75, 51, 45, 63, 58, 9, 98, 31, 46, 13, 43, 85, 17, 50, 98, 9, 84, 67, 98, 4, 48, 20, 81, 70, 2, 6, 68, 44, 78, 79, 91, 24, 68, 47, 82, 60, 39, 59, 98, 89, 18, 49, 52, 26, 15, 6, 22]]
[[[35, 39], [77, 82], [80, 69], [10, 70], [2, 56], [38, 69], [80, 39], [90, 1], [73, 97], [92, 15], [60, 34], [19, 41], [81, 93], [16, 60], [65, 38], [27, 46], [19, 32], [66, 26], [54, 13], [87, 52], [36, 52], [8

In [6]:
#如何從一個陣列中，找出出現頻率最高的數值與位置？
import numpy as np

np.random.seed(0)
a = np.random.randint(0,10,50)
print(a)

counts = np.bincount(a)
print(counts)  #how many elements from 0,1,2,3,4,5...
print("most frequent number is : " + str(np.argmax(counts)))

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3 3
 7 0 1 9 9 0 4 7 3 2 7 2 0]
[ 6  4  4 10  3  4  2  7  5  5]
most frequent number is : 3
