In [2]:
import numpy as np

#[簡答題] 請問下列這三種方法有什麼不同？
a=np.array([1,2,3,6,7,8])
print(a.sum())  #ndarray.sum()
print(np.sum(a))  #numpy 的sum方法，適合處理np array
print(sum(a))  #python 內建的sum方法。適合對list處理

27
27
27


In [3]:
#請對一個 5x5 的隨機矩陣作正規化的操作。
#b = np.arange(1,26)
b= np.random.rand(26)
print(b)
b.resize([5,5])
print(b)

[0.70413717 0.55264344 0.4090001  0.94515459 0.59676627 0.85253968
 0.88082892 0.73807525 0.91878655 0.67187485 0.2044707  0.40902934
 0.94831007 0.61702451 0.49045928 0.35889414 0.5253912  0.67909669
 0.63914094 0.71100473 0.80540822 0.3670294  0.52822757 0.36935428
 0.09495479 0.66986916]
[[0.70413717 0.55264344 0.4090001  0.94515459 0.59676627]
 [0.85253968 0.88082892 0.73807525 0.91878655 0.67187485]
 [0.2044707  0.40902934 0.94831007 0.61702451 0.49045928]
 [0.35889414 0.5253912  0.67909669 0.63914094 0.71100473]
 [0.80540822 0.3670294  0.52822757 0.36935428 0.09495479]]


In [4]:
#請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
c = np.random.randint(100, size=10)
print(c)
np.argmax(c)
c[np.argmax(c)] = -1
print(c)

[58 25 22  3 34 83 92 54 90 65]
[58 25 22  3 34 83 -1 54 90 65]
