In [3]:
# Questions:

#1
import numpy as np
x = np.array([[1,2,3],[1,3,5],[3,3,3]])
print(list(x))
print(x.tolist())

[array([1, 2, 3]), array([1, 3, 5]), array([3, 3, 3])]
[[1, 2, 3], [1, 3, 5], [3, 3, 3]]


In [2]:
#2
#ndarray.itemsize： 陣列中每個元素佔用的空間
#ndarray.data： 陣列所存在的記憶體位置
a=np.random.randint(10,size=6)
b=np.random.randint(10,size=(3,4))
c=np.random.randint(10,size=(2,3,2))
print( 'a: ndim shape size dtype itemsize data')
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)
print( 'b: ndim shape size dtype itemsize data')
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.data)
print( 'c: ndim shape size dtype itemsize data')
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(c.data)

a: ndim shape size dtype itemsize data
[8 4 1 2 6 1]
1
(6,)
6
int64
8
b: ndim shape size dtype itemsize data
[[4 5 7 7]
 [0 3 6 3]
 [1 8 9 0]]
2
(3, 4)
12
int64
8
c: ndim shape size dtype itemsize data
[[[3 1]
  [3 8]
  [5 9]]

 [[6 1]
  [7 1]
  [1 1]]]
3
(2, 3, 2)
12
int64
8


In [4]:
#q3
def tolist(iterable):
  if type(iterable) != np.ndarray:  
      return iterable
  newlist=[]
  for obj in iterable:
      newlist.append(tolist(obj))
  return list(newlist)

print(a)
print(tolist(tolist(a)))
print(b)
print(tolist(tolist(b)))
print(c)
print(tolist(tolist(c)))


[8 4 1 2 6 1]
[8, 4, 1, 2, 6, 1]
[[4 5 7 7]
 [0 3 6 3]
 [1 8 9 0]]
[[4, 5, 7, 7], [0, 3, 6, 3], [1, 8, 9, 0]]
[[[3 1]
  [3 8]
  [5 9]]

 [[6 1]
  [7 1]
  [1 1]]]
[[[3, 1], [3, 8], [5, 9]], [[6, 1], [7, 1], [1, 1]]]
