In [4]:
#1. [簡答題] 請問下列程式碼，運算結果分別為何？
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a+a)
print(a+b)
print(a+c)
print(a+d)
#print(a+e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


In [5]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)
print((A+B)*(-A/2))

C=[]
for index in range(A.shape[0]):
    C.append( (A[index]+B[index]) * ((-1)*A[index]/2) )

print(np.array(C))

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


In [6]:
A = np.ones((1,6))
B = np.ones((6,1))

print(np.dot(A,B)) #內積
#print(np.cross(A,B)) #外積

#print(A * B)
#print(A @ B)

[[6.]]
