In [2]:
import numpy as np

In [3]:
#產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
a=np.arange(12)
print(a)

for i in range(3,7):    
    a[a==i] = -1 * a[a==i] 

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2 -3 -4 -5 -6  7  8  9 10 11]


In [4]:
#試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
x= np.random.randint(10,size=20)
x=x/10
print(x)
print(x[x>0.5])
print(len(x[x>0.5]))

[0.5 0.3 0.4 0.9 0.6 0.  0.8 0.8 0.9 0.7 0.5 0.1 0.8 0.7 0.4 0.  0.8 0.2
 0.7 0.8]
[0.9 0.6 0.8 0.8 0.9 0.7 0.8 0.7 0.8 0.7 0.8]
11
