In [1]:
import numpy as np
print(np.zeros((2,3))) # set all memory value to 0, and it's faster
print(np.empty((3,4))) # memory uninitialized

[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.28822975e-231 -4.34144305e-311  4.96964875e+223  2.55390526e-081]
 [ 1.49460942e+195  9.17796746e+199  1.92526837e+161  3.65881474e+233]
 [ 1.38519249e+219  3.13482157e-086  1.00116594e-312  8.34404900e-309]]


In [2]:
#a = np.arange(1.1,99.7,2.3)
#print(a)
#print(a.astype('int'))


from numpy.random import default_rng
rng = default_rng()
randomm = rng.random((5,5))*100
print(randomm)
print(randomm.astype('int'))

[[ 0.26135477  9.60912585 86.81662627 54.79685534 37.8536578 ]
 [25.72632052 33.09270548  2.33782277 43.04035163 10.06465593]
 [56.12396558 85.65689649 41.10975017 70.60480067 67.04880929]
 [92.29121711 30.14570894 59.8795754  68.4786995  94.93196012]
 [36.93526166  0.33922759 73.45737381 19.67363899 37.03779953]]
[[ 0  9 86 54 37]
 [25 33  2 43 10]
 [56 85 41 70 67]
 [92 30 59 68 94]
 [36  0 73 19 37]]


In [3]:
from numpy.random import default_rng
rng = default_rng()
randommm = rng.integers(5, 10, size=(5,5))

print(randommm)

[[8 5 8 8 7]
 [6 7 5 6 5]
 [8 5 7 7 6]
 [7 8 9 8 7]
 [6 7 8 5 6]]
